### ISSUE TITLE
`zcml`: determine `provides` for `subscriber` if not specified (as for `adapter`)

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/zope.component#40] opened 2019-04-05 09:42 UTC
`zope.component.zcml.adapter` determines `provides` automatically when it is not specified.

Sometimes, `subscriber` is used to register an adapter (the so called `subscription adapter`s).  It would be natural when it treated `provides` in this case in the same way as `adpater`.

**Comment by jamadden** [comment] 2021-03-18 13:06
Duplicate of #9.

**Closed by jamadden** 2021-03-18 13:06 UTC
Labels: enhancement
